---
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# | Fast Config - Ths is the most basic configuration for a fast deploy
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

# |                              ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
private_ip   : &private_ip      '10.0.0.10'
vagrant_box  : &vagrant_box     'bento/ubuntu-16.04'

machine_name : &machine_name    'vag-ubuntu'
machine_ram  : &machine_ram     'auto'
machine_cpu  : &machine_cpu     'auto'
# |                              ↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑↑

# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
# | ### Config VirtualBox VM
# | ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

vms:
  - name               : *machine_name
    box                : *vagrant_box
    # box_version        : 2.2.9
    box_check_update   : false
    ram                : *machine_ram
    cpus               : *machine_cpu

    # | ······ Defining Netword
    private_network :
      ip_private       : *private_ip
      # auto_config      : false
      # type             : dhcp

    public_network :
      # ip_public        : auto # Basic Config
      # ip_public        : true # Using the DHCP Assigned Default Route
      # ip_public        : 192.168.0.70
      # bridge           : 'eth0'

    # | ······ Defining a Forwarded Port
    ports :
      - guest          : 3000
        host           : 3000

      # - guest          : 80
      #   host           : 8080

    # | ······ Config Synced folders
    syncDir :
      - host           : share
        guest          : /home/vagrant/share
        dmode          : 766
        fmode          : 766

      # - host           : www
      #   guest          : /home/vagrant/www
      #   owner          : www-data
      #   group          : www-data
      #   dmode          : 775
      #   fmode          : 775

    # | ······ GUI
    # gui   : true

    # | ······ Bash provision
    # bash  : bash/init.sh

# ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░..
